<a href="https://colab.research.google.com/github/davism02/Project-4-Predicting-Hospial-Readmission-for-Diabetes/blob/main/diabetes_nn_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
url ='https://raw.githubusercontent.com/uvineet53/optum_22/main/Resources/final_data.csv'

In [2]:
#Loading libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

In [4]:
df = pd.read_csv(url)
df.head()

   Unnamed: 0  age  time_in_hospital  ...  readmitted  race  gender
0           0   15                 3  ...           0     2       0
1           1   25                 2  ...           0     0       0
2           2   35                 2  ...           0     2       1
3           3   45                 1  ...           0     2       1
4           4   55                 3  ...           0     2       1

[5 rows x 8 columns]

In [5]:
df.drop(['Unnamed: 0'], axis=1,inplace=True)
df

       age  time_in_hospital  num_procedures  ...  readmitted  race  gender
0       15                 3               0  ...           0     2       0
1       25                 2               5  ...           0     0       0
2       35                 2               1  ...           0     2       1
3       45                 1               0  ...           0     2       1
4       55                 3               6  ...           0     2       1
...    ...               ...             ...  ...         ...   ...     ...
98047   75                 3               0  ...           0     0       1
98048   85                 5               3  ...           0     0       0
98049   75                 1               0  ...           0     2       1
98050   85                10               2  ...           0     2       0
98051   75                 6               3  ...           0     2       1

[98052 rows x 7 columns]

In [6]:
# Split our preprocessed data into our features and target arrays
y = df['readmitted']
X = df.drop(columns = ["readmitted"], axis=1)
X

       age  time_in_hospital  num_procedures  num_medications  race  gender
0       15                 3               0               18     2       0
1       25                 2               5               13     0       0
2       35                 2               1               16     2       1
3       45                 1               0                8     2       1
4       55                 3               6               16     2       1
...    ...               ...             ...              ...   ...     ...
98047   75                 3               0               16     0       1
98048   85                 5               3               18     0       0
98049   75                 1               0                9     2       1
98050   85                10               2               21     2       0
98051   75                 6               3                3     2       1

[98052 rows x 6 columns]

In [7]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state= 42)

In [8]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Compile, Train and Evalutate the Model

In [9]:
## Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 49

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 21)                315

 dense_3 (Dense)             (None, 1)                 22

=================================================================
Total params: 498
Trainable params: 498
Non-trainable params: 0
_________________________________________________________________

In [10]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [11]:
# Train the model
import timeit
start = timeit.timeit()
end = timeit.timeit()

fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)
print(f'Time to Run: {end - start} seconds')

Epoch 1/100
1954/1954 [==============================] - 5s 2ms/step - loss: 0.3630 - accuracy: 0.8850 - val_loss: 0.3632 - val_accuracy: 0.8817
Epoch 2/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3529 - accuracy: 0.8866 - val_loss: 0.3624 - val_accuracy: 0.8817
Epoch 3/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3521 - accuracy: 0.8866 - val_loss: 0.3610 - val_accuracy: 0.8817
Epoch 4/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3520 - accuracy: 0.8866 - val_loss: 0.3611 - val_accuracy: 0.8817
Epoch 5/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3519 - accuracy: 0.8866 - val_loss: 0.3621 - val_accuracy: 0.8817
Epoch 6/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3516 - accuracy: 0.8866 - val_loss: 0.3630 - val_accuracy: 0.8817
Epoch 7/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3517 - accuracy: 0.8866 - val_loss: 0.3614 - val_accuracy: 0.8817
Epoch 8/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3515 - accuracy: 0.8866 - val_loss: 0.3617 - val_accuracy: 0.8817
Epoch 9/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3514 - accuracy: 0.8866 - val_loss: 0.3621 - val_accuracy: 0.8817
Epoch 10/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3515 - accuracy: 0.8866 - val_loss: 0.3612 - val_accuracy: 0.8817
Epoch 11/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3513 - accuracy: 0.8866 - val_loss: 0.3625 - val_accuracy: 0.8817
Epoch 12/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3512 - accuracy: 0.8866 - val_loss: 0.3619 - val_accuracy: 0.8817
Epoch 13/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3513 - accuracy: 0.8866 - val_loss: 0.3614 - val_accuracy: 0.8817
Epoch 14/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3512 - accuracy: 0.8866 - val_loss: 0.3612 - val_accuracy: 0.8817
Epoch 15/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3512 - accuracy: 0.8866 - val_loss: 0.3618 - val_accuracy: 0.8817
Epoch 16/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3512 - accuracy: 0.8866 - val_loss: 0.3610 - val_accuracy: 0.8817
Epoch 17/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3512 - accuracy: 0.8866 - val_loss: 0.3610 - val_accuracy: 0.8817
Epoch 18/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3511 - accuracy: 0.8866 - val_loss: 0.3616 - val_accuracy: 0.8817
Epoch 19/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3511 - accuracy: 0.8866 - val_loss: 0.3614 - val_accuracy: 0.8817
Epoch 20/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3510 - accuracy: 0.8866 - val_loss: 0.3609 - val_accuracy: 0.8817
Epoch 21/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3509 - accuracy: 0.8866 - val_loss: 0.3621 - val_accuracy: 0.8817
Epoch 22/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3510 - accuracy: 0.8866 - val_loss: 0.3619 - val_accuracy: 0.8817
Epoch 23/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3510 - accuracy: 0.8866 - val_loss: 0.3638 - val_accuracy: 0.8817
Epoch 24/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3510 - accuracy: 0.8866 - val_loss: 0.3614 - val_accuracy: 0.8817
Epoch 25/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3507 - accuracy: 0.8866 - val_loss: 0.3617 - val_accuracy: 0.8817
Epoch 26/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3508 - accuracy: 0.8866 - val_loss: 0.3633 - val_accuracy: 0.8817
Epoch 27/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3508 - accuracy: 0.8866 - val_loss: 0.3614 - val_accuracy: 0.8817
Epoch 28/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3507 - accuracy: 0.8866 - val_loss: 0.3615 - val_accuracy: 0.8817
Epoch 29/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3508 - accuracy: 0.8866 - val_loss: 0.3615 - val_accuracy: 0.8817
Epoch 30/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3508 - accuracy: 0.8866 - val_loss: 0.3623 - val_accuracy: 0.8817
Epoch 31/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3506 - accuracy: 0.8866 - val_loss: 0.3613 - val_accuracy: 0.8817
Epoch 32/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3506 - accuracy: 0.8866 - val_loss: 0.3611 - val_accuracy: 0.8817
Epoch 33/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3507 - accuracy: 0.8866 - val_loss: 0.3615 - val_accuracy: 0.8817
Epoch 34/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3506 - accuracy: 0.8866 - val_loss: 0.3620 - val_accuracy: 0.8817
Epoch 35/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3505 - accuracy: 0.8866 - val_loss: 0.3612 - val_accuracy: 0.8817
Epoch 36/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3506 - accuracy: 0.8866 - val_loss: 0.3613 - val_accuracy: 0.8817
Epoch 37/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3506 - accuracy: 0.8866 - val_loss: 0.3616 - val_accuracy: 0.8817
Epoch 38/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3505 - accuracy: 0.8866 - val_loss: 0.3613 - val_accuracy: 0.8817
Epoch 39/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3504 - accuracy: 0.8866 - val_loss: 0.3619 - val_accuracy: 0.8817
Epoch 40/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3505 - accuracy: 0.8866 - val_loss: 0.3613 - val_accuracy: 0.8817
Epoch 41/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3503 - accuracy: 0.8866 - val_loss: 0.3617 - val_accuracy: 0.8817
Epoch 42/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3505 - accuracy: 0.8866 - val_loss: 0.3614 - val_accuracy: 0.8817
Epoch 43/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3505 - accuracy: 0.8866 - val_loss: 0.3620 - val_accuracy: 0.8817
Epoch 44/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3505 - accuracy: 0.8866 - val_loss: 0.3615 - val_accuracy: 0.8817
Epoch 45/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3504 - accuracy: 0.8866 - val_loss: 0.3612 - val_accuracy: 0.8817
Epoch 46/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3504 - accuracy: 0.8866 - val_loss: 0.3619 - val_accuracy: 0.8817
Epoch 47/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3505 - accuracy: 0.8866 - val_loss: 0.3614 - val_accuracy: 0.8817
Epoch 48/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3503 - accuracy: 0.8866 - val_loss: 0.3617 - val_accuracy: 0.8817
Epoch 49/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3503 - accuracy: 0.8866 - val_loss: 0.3620 - val_accuracy: 0.8817
Epoch 50/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3503 - accuracy: 0.8866 - val_loss: 0.3613 - val_accuracy: 0.8817
Epoch 51/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3502 - accuracy: 0.8866 - val_loss: 0.3615 - val_accuracy: 0.8817
Epoch 52/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3503 - accuracy: 0.8866 - val_loss: 0.3622 - val_accuracy: 0.8817
Epoch 53/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3502 - accuracy: 0.8866 - val_loss: 0.3612 - val_accuracy: 0.8817
Epoch 54/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3502 - accuracy: 0.8866 - val_loss: 0.3612 - val_accuracy: 0.8817
Epoch 55/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3503 - accuracy: 0.8866 - val_loss: 0.3625 - val_accuracy: 0.8817
Epoch 56/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3503 - accuracy: 0.8866 - val_loss: 0.3618 - val_accuracy: 0.8817
Epoch 57/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3501 - accuracy: 0.8866 - val_loss: 0.3619 - val_accuracy: 0.8817
Epoch 58/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3501 - accuracy: 0.8866 - val_loss: 0.3616 - val_accuracy: 0.8817
Epoch 59/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3502 - accuracy: 0.8866 - val_loss: 0.3611 - val_accuracy: 0.8817
Epoch 60/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3502 - accuracy: 0.8866 - val_loss: 0.3617 - val_accuracy: 0.8817
Epoch 61/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3500 - accuracy: 0.8866 - val_loss: 0.3617 - val_accuracy: 0.8817
Epoch 62/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3502 - accuracy: 0.8866 - val_loss: 0.3627 - val_accuracy: 0.8817
Epoch 63/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3501 - accuracy: 0.8866 - val_loss: 0.3613 - val_accuracy: 0.8817
Epoch 64/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3501 - accuracy: 0.8866 - val_loss: 0.3622 - val_accuracy: 0.8817
Epoch 65/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3501 - accuracy: 0.8866 - val_loss: 0.3615 - val_accuracy: 0.8817
Epoch 66/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3502 - accuracy: 0.8866 - val_loss: 0.3620 - val_accuracy: 0.8817
Epoch 67/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3501 - accuracy: 0.8866 - val_loss: 0.3611 - val_accuracy: 0.8817
Epoch 68/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3501 - accuracy: 0.8866 - val_loss: 0.3625 - val_accuracy: 0.8817
Epoch 69/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3502 - accuracy: 0.8866 - val_loss: 0.3614 - val_accuracy: 0.8817
Epoch 70/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3501 - accuracy: 0.8866 - val_loss: 0.3618 - val_accuracy: 0.8817
Epoch 71/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3501 - accuracy: 0.8866 - val_loss: 0.3616 - val_accuracy: 0.8817
Epoch 72/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3500 - accuracy: 0.8866 - val_loss: 0.3613 - val_accuracy: 0.8817
Epoch 73/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3500 - accuracy: 0.8866 - val_loss: 0.3621 - val_accuracy: 0.8817
Epoch 74/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3500 - accuracy: 0.8866 - val_loss: 0.3617 - val_accuracy: 0.8817
Epoch 75/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3500 - accuracy: 0.8866 - val_loss: 0.3620 - val_accuracy: 0.8817
Epoch 76/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3499 - accuracy: 0.8866 - val_loss: 0.3616 - val_accuracy: 0.8817
Epoch 77/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3500 - accuracy: 0.8866 - val_loss: 0.3615 - val_accuracy: 0.8817
Epoch 78/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3499 - accuracy: 0.8866 - val_loss: 0.3625 - val_accuracy: 0.8817
Epoch 79/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3500 - accuracy: 0.8866 - val_loss: 0.3615 - val_accuracy: 0.8817
Epoch 80/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3500 - accuracy: 0.8866 - val_loss: 0.3618 - val_accuracy: 0.8817
Epoch 81/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3499 - accuracy: 0.8866 - val_loss: 0.3620 - val_accuracy: 0.8817
Epoch 82/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3499 - accuracy: 0.8866 - val_loss: 0.3623 - val_accuracy: 0.8817
Epoch 83/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3499 - accuracy: 0.8866 - val_loss: 0.3616 - val_accuracy: 0.8817
Epoch 84/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3500 - accuracy: 0.8866 - val_loss: 0.3614 - val_accuracy: 0.8817
Epoch 85/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3498 - accuracy: 0.8866 - val_loss: 0.3621 - val_accuracy: 0.8817
Epoch 86/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3498 - accuracy: 0.8866 - val_loss: 0.3613 - val_accuracy: 0.8817
Epoch 87/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3499 - accuracy: 0.8866 - val_loss: 0.3622 - val_accuracy: 0.8817
Epoch 88/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3498 - accuracy: 0.8866 - val_loss: 0.3618 - val_accuracy: 0.8817
Epoch 89/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3496 - accuracy: 0.8866 - val_loss: 0.3615 - val_accuracy: 0.8817
Epoch 90/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3498 - accuracy: 0.8866 - val_loss: 0.3617 - val_accuracy: 0.8817
Epoch 91/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3498 - accuracy: 0.8866 - val_loss: 0.3619 - val_accuracy: 0.8817
Epoch 92/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3500 - accuracy: 0.8866 - val_loss: 0.3621 - val_accuracy: 0.8817
Epoch 93/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3497 - accuracy: 0.8866 - val_loss: 0.3613 - val_accuracy: 0.8817
Epoch 94/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3497 - accuracy: 0.8866 - val_loss: 0.3617 - val_accuracy: 0.8817
Epoch 95/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3499 - accuracy: 0.8866 - val_loss: 0.3613 - val_accuracy: 0.8817
Epoch 96/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3498 - accuracy: 0.8866 - val_loss: 0.3622 - val_accuracy: 0.8817
Epoch 97/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3497 - accuracy: 0.8866 - val_loss: 0.3619 - val_accuracy: 0.8817
Epoch 98/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3498 - accuracy: 0.8866 - val_loss: 0.3617 - val_accuracy: 0.8817
Epoch 99/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3497 - accuracy: 0.8866 - val_loss: 0.3620 - val_accuracy: 0.8817
Epoch 100/100
1954/1954 [==============================] - 4s 2ms/step - loss: 0.3498 - accuracy: 0.8866 - val_loss: 0.3617 - val_accuracy: 0.8817
Time to Run: -0.0010439720000192665 seconds

In [12]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print('Model: Neural Network')
print(f'Time to Run: {end - start} seconds')
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

767/767 - 1s - loss: 0.3439 - accuracy: 0.8910 - 779ms/epoch - 1ms/step
Model: Neural Network
Time to Run: -0.0010439720000192665 seconds
Loss: 0.34390416741371155, Accuracy: 0.8909966349601746

In [14]:
# Export our model to HDF5 file
from google.colab import files

nn.save('/content/Model_1.h5')
files.download('/content/Model_1.h5')